gnu: python-futures: Enable tests.
Re-enable the tests, as the python-2 package now has the support
directory. Also, switch to running the tests via the test_futures.py script to
avoid errors like:

  AttributeError: 'AsCompletedTests' object has no attribute 'executor'

* gnu/packages/python.scm (python2-futures)[arguments]: Run the
test_futures.py script to run the tests.