gnu: qt-4: Do not set $LDFLAGS since that triggerred a build failure.
Fixes the build failure at <http://hydra.gnu.org/build/379884/log/raw>:

  g++ -licui18n -Wl,-O1 [...] -o ../../../../bin/assistant [...]
  ld: warning: libQtCLucene.so.4, needed by /tmp/nix-build-qt-4.8.6.drv-0/qt-everywhere-opensource-src-4.8.6/lib/libQtHelp.so, not found (try using -rpath or -rpath-link)
  /tmp/nix-build-qt-4.8.6.drv-0/qt-everywhere-opensource-src-4.8.6/lib/libQtHelp.so: undefined reference to `QCLucenePhraseQuery::getTerms() const'
  [...]

* gnu/packages/patches/qt4-ldflags.patch: New file.
* gnu-system.am (dist_patch_DATA): Add it.
* gnu/packages/qt.scm (qt-4)[source]: Use it.
  [arguments]: Remove 'setenv' call in 'configure' phase.