gnu: rtl8821ce-linux-module: Update to 0.0.0-4-ca204c6.
Fixes compatibility with linux-libre@5.15:

  […]/source/core/rtw_br_ext.c:20:11: fatal error: net/ipx.h:
  No such file or directory
    #include <net/ipx.h>
             ^~~~~~~~~~~
  compilation terminated.

* gnu/packages/linux.scm (rtl8821ce-linux-module):
Update to 0.0.0-4-ca204c6.

Signed-off-by: Tobias Geerinckx-Rice <me@tobias.gr>