gnu: coreutils: Fix cross-compilation.
Fix coreutils cross-compilation for aarch64 that was broken by 8.32
update. The following error occured:

src/ls.c: In function 'print_dir':
src/ls.c:3026:24: error: 'SYS_getdents' undeclared (first use in this function); did you mean 'SYS_getdents64'?
           if (syscall (SYS_getdents, dirfd (dirp), NULL, 0) == -1
                        ^~~~~~~~~~~~
                        SYS_getdents64

* gnu/packages/patches/coreutils-ls.patch: New file.
* gnu/local.mk (dist_patch_DATA): Add it.
* gnu/packages/base.scm (coreutils): Apply it.