Revert "gnu: grub: Fix unicode font loading when booting over TFTP."
This reverts commit 03fb57ff77b57de510b59485845ed7cb4e0a77a7, which
breaks most system tests.  Specifically, grub.cfg.drv fails to build:

  ERROR: In procedure canonicalize-path:
  In procedure canonicalize-path: No such file or directory