gnu: coreutils: Fix cross-compilation to i586-pc-gnu.
Until now cross-compilation would fail with:

  i586-pc-gnu-ld: src/copy.o: undefined reference to symbol 'file_chauthor'
  i586-pc-gnu-ld: /gnu/store/…-glibc-cross-i586-pc-gnu-2.29/lib/libhurduser.so.0.3: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status

* gnu/packages/base.scm (coreutils)[arguments]: When 'hurd-target?', add
 #:configure-flags.