Re-order the armhf linux-libre kernel packages to fix the build.
This is a followup to commit 37f8c50cdc2e99189c74999319f3a1854d419546.

Previously, building Guix crashed like this:

------
In ice-9/eval.scm:
    619:8  4 (_ #f)
   626:19  3 (_ #<directory (gnu packages linux) 7fcf3e526c80>)
    159:9  2 (_ #<directory (gnu packages linux) 7fcf3e526c80>)
   223:20  1 (proc #<directory (gnu packages linux) 7fcf3e526c80>)
In unknown file:
           0 (%resolve-variable (7 . linux-libre-arm-generic) #<directory (gnu packages linux) 7fcf3e526c80>)

ERROR: In procedure %resolve-variable:
error: linux-libre-arm-generic: unbound variable
------

* gnu/packages/linux.scm (linux-libre-arm-veyron): Move after
linux-libre-arm-generic.