gnu: python-parsedatetime: Update to 2.3.
Version 2.1 was apparently time-sensitive and started failing like this:

  ======================================================================
  FAIL: testFloat (tests.TestDelta.test)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/guix-build-python2-parsedatetime-2.1.drv-0/parsedatetime-2.1/tests/TestDelta.py", line 64, in testFloat
      self.cal.parse('1.4 months ago', self.source), months=-1.4)
    File "/tmp/guix-build-python2-parsedatetime-2.1.drv-0/parsedatetime-2.1/tests/TestDelta.py", line 37, in assertDelta
      self.assertTrue(diff < 0.05, '%s is not less than 0.05' % diff)
  AssertionError: 0.0666666666667 is not less than 0.05

  ----------------------------------------------------------------------

* gnu/packages/python.scm (python-parsedatetime): Update to 2.3.
[native-inputs]: Add PYTHON-PYTEST and PYTHON-PYTEST-RUNNER.
[propagated-inputs]: New field.