Revert "guix: git: Add new module."
This reverts commit a70b784708fb5e1b78430aa793d89ca04bc641a8.

Commit a70b784708f caused `guix pull` to fail:

ERROR: In procedure scm-error:
ERROR: no code for module (git)