gnu: mysql: Fix build.
MySQL demands boost@1.59.0, and lying about it no longer works:

sql/item_geofunc_internal.cc: In function ‘void handle_gis_exception(const char*)’:
sql/item_geofunc_internal.cc:37:81: error: expected unqualified-id before ‘&’ token
   catch (const boost::geometry::detail::self_get_turn_points::self_ip_exception &)
                                                                                 ^
[...]

* gnu/packages/databases.scm (boost-for-mysql): New variable.
(mysql)[inputs]: Use that instead of the regular boost.
[arguments]: Remove now-unnecessary ‘patch-boost-version’ phase.