Revert "gnu: Fix Krita."
This reverts commit 5f63905096e456097fca206f56ce9257f72faf64.

This commit caused `guix pull` to crash like this:

------
Backtrace:
In ice-9/boot-9.scm:
   222:29 19 (map1 _)
   222:29 18 (map1 _)
   222:29 17 (map1 _)
   222:29 16 (map1 _)
   222:17 15 (map1 (((gnu packages kde)) ((gnu packages libevent)) ((gnu packages libidn)) ((gnu packages #)) ((?)) ?))
  3297:17 14 (resolve-interface (gnu packages kde) #:select _ #:hide _ #:prefix _ #:renamer _ #:version _)
In ice-9/threads.scm:
    390:8 13 (_ _)
In ice-9/boot-9.scm:
  3223:13 12 (_)
In ice-9/threads.scm:
    390:8 11 (_ _)
In ice-9/boot-9.scm:
  3507:20 10 (_)
   2806:4  9 (save-module-excursion _)
  3527:26  8 (_)
In unknown file:
           7 (primitive-load-path "gnu/packages/kde" #<procedure 7f68d6fe5da0 at ice-9/boot-9.scm:3514:37 ()>)
In ice-9/eval.scm:
   626:19  6 (_ #<directory (gnu packages kde) 7f68d6175b40>)
   293:34  5 (_ #<directory (gnu packages kde) 7f68d6175b40>)
   173:47  4 (_ #(#<directory (gnu packages kde) 7f68d6175b40> #<promise #<procedure 7f68dc5a5d00 at ice-9/eval.sc?>))
    159:9  3 (_ #(#<directory (gnu packages kde) 7f68d6175b40> #<promise #<procedure 7f68dc5a5d00 at ice-9/eval.sc?>))
   191:35  2 (_ #(#<directory (gnu packages kde) 7f68d6175b40> #<promise #<procedure 7f68dc5a5d00 at ice-9/eval.sc?>))
   223:20  1 (proc #(#<directory (gnu packages kde) 7f68d6175b40> #<promise #<procedure 7f68dc5a5d00 at ice-9/eval?>))
In unknown file:
           0 (%resolve-variable (7 . qtbase) #<directory (gnu packages kde) 7f68d6175b40>)

ERROR: In procedure %resolve-variable:
error: qtbase: unbound variable
------