gnu: openmpi: Upgrade to 4.0.0.
* gnu/packages/linux.scm (psm)[arguments]: Add 'patch-sysmacros phase to fix
"undefined reference to `minor'" errors while linking against
libinfinipath.so.
* gnu/packages/mpi.scm (openmpi): Upgrade to 4.0.0.
[inputs]: Add libevent.
[arguments]: Simplify configure-flags.  Use system libevent.  Adjust romio
version strings.
(%openmpi-setup): Use OMPI_MCA_rmaps_base_mapping_policy for oversubscription.