gnu: python-pyside-2: Propagate python-shiboken-2.
Importing PySide2 failed, because shiboken was not propagated. Testcase:

> guix environment --ad-hoc python python-pyside-2 -- python -c 'import PySide2'
PySide2/__init__.py: Unable to import shiboken2 from , /gnu/store/vpniba85hhzb2270hki61z0d2kfvb64l-profile/lib/python3.8/site-packages, /usr/lib/python38.zip, /usr/lib/python3.8, /usr/lib/python3.8/lib-dynload, /usr/lib/python3.8/site-packages
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gnu/store/vpniba85hhzb2270hki61z0d2kfvb64l-profile/lib/python3.8/site-packages/PySide2/__init__.py", line 91, in <module>
    _setupQtDirectories()
  File "/gnu/store/vpniba85hhzb2270hki61z0d2kfvb64l-profile/lib/python3.8/site-packages/PySide2/__init__.py", line 57, in _setupQtDirectories
    import shiboken2
ModuleNotFoundError: No module named 'shiboken2'

* gnu/packages/qt.scm (python-pyside-2) [native-inputs]: Move from here…
[propagated-inputs]: …to here.