gnu: lapack: Install libraries to PREFIX/lib, not PREFIX/lib64.
This fixes a regression introduced in
ef39a17717a10a7f406730258acfdb07934c7255, which would break
python-scipy ("undefined reference to `zungqr_'").

* gnu/packages/maths.scm (lapack)[arguments]: Add
"-DCMAKE_INSTALL_LIBDIR" to #:configure-flags.