gnu: eog: Fix build with libportal-0.5.
After the update to libportal-0.5 in 294476022f19139e290acb448d4575de0f851673
eog fails with:

../eog-40.3/src/eog-util.c:48:10: fatal error: libportal/portal-gtk3.h: No such file or directory

This was already fixed upstream and this commits extracts the patch.

* gnu/packages/patches/eog-update-libportal-usage.patch: New file.
* gnu/local.mk (dist_patch_DATA): Register it.
* gnu/packages/gnome.scm(eog)[origin]: Add new patch.

Signed-off-by: Guillaume Le Vaillant <glv@posteo.net>