gnu: usbredir: Build without '-Werror'.
Fixes build failure introduced in
58ee8a94a90eb40496b9704d541b5dfbbf1685ba, where compilation would fail
with:

  usbredirhost.c: In function ?usbredirhost_open_full?:
  usbredirhost.c:749:5: error: ?libusb_set_debug? is deprecated: Use libusb_set_option instead [-Werror=deprecated-declarations]
       libusb_set_debug(host->ctx, host->verbose);
       ^
  In file included from usbredirhost.h:24:0,
		   from usbredirhost.c:31:
  /gnu/store/j8hzc465xy33cjfcq3wv39szxia4xrzv-libusb-1.0.22/include/libusb-1.0/libusb.h:1300:18: note: declared here
   void LIBUSB_CALL libusb_set_debug(libusb_context *ctx, int level);
		    ^
  cc1: all warnings being treated as errors

* gnu/packages/spice.scm (usbredir)[arguments]: In 'autogen' phase,
remove '-Werror' from configure.ac.