gnu: lout: Revert changes from dc1d3cdef70f0e3c047c22.
This caused `make` to error out like this:

ERROR: In procedure primitive-load-path:
ERROR: In procedure read_inner_expression: gnu/packages/lout.scm:31:12: unexpected ")"

* gnu/packages/lout.scm (lout)[arguments]: Don't use 'modify-phases'.